server:
  port: 8993

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quartz3

    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            useProperties: true
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          scheduler:
            instanceName: myScheduler
            instanceId: AUTO
